### ISSUE TITLE
shrines of chance don't emit any sound on interaction

### ISSUE THREAD

**Issue by Littleevo** [Xatha/SoCRebalancePlugin#1]
das it.

**Comment by VarnaScelestus** [comment]
Confirming this; with the mod, the interaction sound is gone. Minor, but sad.

**Comment by Xatha** [comment]
Confirmed and reproducible. I will try fix it today, thank you for the heads up.

**Comment by Xatha** [comment]
Sorry for the delay, it should be fixed now :)
