### ISSUE TITLE
Compatibility with Quality of Rain

### ISSUE THREAD

**Issue by ConqAra** [Xatha/SoCRebalancePlugin#2]
Quality of rain makes shrines activate faster, is it possible to make compatibility for mods like this that speed up the chance shrine?

**Comment by Xatha** [comment]
I am currently working on rewriting large parts of my code, to minimise incompatibilities with other mods. I'll try my best to make it compatible with Quality of rain.

**Comment by Xatha** [comment]
I was not able to fix the compatibility issue. But I have added configurations to my mod, where you can configure the activation speed to your liking.
